/**:
  ros__parameters:
    mode: "random"
    world:
      task:
        distribution: "uniform" # `uniform` or `normal`
        normal:
          mean:
            x: 0.0
            y: 0.0
            z: 0.0
          covariance:
            x: 0.5
            y: 0.5
            z: 0.5
      boundary:
        min:
          x: -1.5
          y: -1.5
          z: 0.0
        max:
          x: 1.5
          y: 1.5
          z: 0.0
